//
// Created by mamac on 28/03/2023.
//

#ifndef LANGLOISMATTEODEVOBJET_PROJETSMARTORDERMANAGER_ADMIN_H
#define LANGLOISMATTEODEVOBJET_PROJETSMARTORDERMANAGER_ADMIN_H


class Admin {

};


#endif //LANGLOISMATTEODEVOBJET_PROJETSMARTORDERMANAGER_ADMIN_H
