//
// Created by mamac on 28/03/2023.
//

#ifndef LANGLOISMATTEODEVOBJET_PROJETSMARTORDERMANAGER_COLIS_H
#define LANGLOISMATTEODEVOBJET_PROJETSMARTORDERMANAGER_COLIS_H


class Colis {

};


#endif //LANGLOISMATTEODEVOBJET_PROJETSMARTORDERMANAGER_COLIS_H
