#ifndef LANGLOISMATTEODEVOBJET_PROJETSMARTORDERMANAGER_PERSONNE_H
#define LANGLOISMATTEODEVOBJET_PROJETSMARTORDERMANAGER_PERSONNE_H

#include "string"

using namespace std;

class Personne {
private:
    std::string nom;
    std::string prenom;
};


#endif //LANGLOISMATTEODEVOBJET_PROJETSMARTORDERMANAGER_PERSONNE_H
